name: check lints
on:
  push:
    branches: ["*"]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: check lint
        run: bun run lint

      - name: expo doctor
        run: bunx expo-doctor
